spring:
  application:
    name: myretro
  datasource:
    generate-unique-name: false
    name: test-db
#    url: jdbc:postgresql://localhost:5003/test-db?forceBinary=true&options=-c%20timezone=UTC
  sql:
    init:
      mode: always
service:
  users:
    server: http://127.0.0.1
    port: 8082
    username: admin
    password: aW3s0m3

---
spring:
  config:
    activate:
      on-profile: cloud
service:
  users:
    server: cloud.server.com
    port: 1089
    username: root
    password: Sup3RaW3s0m3